### PR TITLE
Upgrade Cake to 0.17.0

### PR DESCRIPTION
**Pull request by devlead**
Cake 0.18.0 will requires at least version 0.16.x to work.

### CODE REVIEW

**Comment by gep13** [comment]
@marcosnz are you in a position to look at this?

If you are no longer interested in updating your addin's, would you be interested in moving them into the cake-contrib organisation?

**Comment by hurcane** [comment]
I believe the maintainer of this repository died tragically on 22 November 2015. I am interested in being able to use this addin with newer versions of Cake.

I'm not sure what the proper action is in this situation. Should a fork of this repository be made and coordinated with the Cake team? Or maybe the content should be submitted as an integration into the core Cake project? It might fit neatly into the existing MSBuild namespace.

**Comment by devlead** [comment]
@hurcane oh, I was unaware of that, it's tragic news indeed.
For the future of the addin best would be if we could have it transferred to cake-contrib org.
Don't know how GitHub would handle this kind of scenario, but I'll email support and ask, guess they would need to verify.
We can always fork, but that's not ideel.
@marcosnz  is also owner of NuGet package so would need to check with them too.

**Comment by gep13** [comment]
@hurcane thank you for reaching out, this is obviously terrible news if this is indeed that case.  Do you have account on gitter.im? I would like to talk to you about this, but think it best not in a public forum. Could you contact me directly via private message in gitter.im? Thank you!

**Comment by martpendle** [comment]
That is sad news. 

In terms of the project I would be interested to know what the outcomes are.

**Comment by devlead** [comment]
@martpendle project has been forked to [cake-contrib/Cake.MSBuildTask](https://github.com/cake-contrib/Cake.MSBuildTask) and cake-contrib has now been made owner of the nuget package [Cake.MSBuildTask](https://www.nuget.org/packages/Cake.MSBuildTask/). so development can continue in that fork.

**Comment by devlead** [comment]
I've opened this PR to the fork instead
cake-contrib/Cake.MSBuildTask/pull/4

**Pull request closed without merging**
